const ON_USER_LOGGED = 'ON_USER_LOGGED';
const ON_USER_LOGOUT = 'ON_USER_LOGOUT';
const ON_LOAD_ENVIOS = 'ON_LOAD_ENVIOS';
const ON_ADD_ENVIO = 'ON_ADD_ENVIO';
const ON_DELETE_ENVIO = 'ON_DELETE_ENVIO';
const GET_CATEGORIAS = 'GET_CATEGORIAS';
const GET_CIUDADES = 'GET_CIUDADES';
const GET_DEPTOS = 'GET_DEPTOS';


export { ON_USER_LOGGED, ON_LOAD_ENVIOS, ON_ADD_ENVIO, ON_DELETE_ENVIO, GET_CATEGORIAS, GET_CIUDADES, GET_DEPTOS, ON_USER_LOGOUT };

